schooldata = [
    {
        "name": "Tavanappa Patane High School",
        "poshanid": "01",
        "studentscount": 320,
        "incharge": "Divya Reddy",
        "contact": "9220342742",
        "address": "Rajarampuri",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Lokmanya Vidyalaya",
        "poshanid": "02",
        "studentscount": 320,
        "incharge": "Ishaan Bhatia",
        "contact": "9985439435",
        "address": "Kolhapur",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Kolhapur Municipal School No 9",
        "poshanid": "03",
        "studentscount": 320,
        "incharge": "Aanya Chopra",
        "contact": "9396084383",
        "address": "Kolhapur",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Rajashri Shahu Vidya Mandir",
        "poshanid": "04",
        "studentscount": 320,
        "incharge": "Aarav Gupta",
        "contact": "9768708022",
        "address": "Kolhapur",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Zilla Parishad Primary School",
        "poshanid": "05",
        "studentscount": 320,
        "incharge": "Sanjana Shah",
        "contact": "9269725568",
        "address": "Kolhapur",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Vidya Mandir",
        "poshanid": "06",
        "studentscount": 320,
        "incharge": "Avni Patel",
        "contact": "9354149519",
        "address": "Kumbharwadi",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Government Ashram School",
        "poshanid": "07",
        "studentscount": 320,
        "incharge": "Manav Jain",
        "contact": "9680294970",
        "address": "Borbet",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Government Ashram School",
        "poshanid": "08",
        "studentscount": 320,
        "incharge": "Arnav Desai",
        "contact": "9981430077",
        "address": "Kote",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Vidya Mandir",
        "poshanid": "09",
        "studentscount": 320,
        "incharge": "Kiara Kumar",
        "contact": "9678403390",
        "address": "Sakhari",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
    {
        "name": "Sutarwadi Govt Primary School",
        "poshanid": "10",
        "studentscount": 320,
        "incharge": "Advait Agarwal",
        "contact": "9977144247",
        "address": "Kolhapur",
        "menuupdatetime": "03/12/23",
        "menu": [],
    },
]
